apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etl-app
  template:
    metadata:
      labels:
        app: etl-app
    spec:
      containers:
        - name: etl-app
          image: nicoxdockerhub/etl-app:latest # Replace with your image location if pushed to a registry
