apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etl-app
  template:
    metadata:
      labels:
        app: etl-app
    spec:
      containers:
        - name: etl-app
          image: nicoxdockerhub/etl-app:latest 
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          periodSeconds: 30     # Adjust the periodSeconds value
          timeoutSeconds: 30     # Adjust the timeoutSeconds value
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          periodSeconds: 30     # Adjust the periodSeconds value
          timeoutSeconds: 30     # Adjust the timeoutSeconds value
